import type { Metadata } from "next";
import "@/app/globals.css";

import SplashScreen from "@/components/ui/SplashScreen";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className="antialiased">
        <SplashScreen />
        <main>{children}</main>
      </body>
    </html>
  );
}
